spring.application.name=ProductService
server.port=5000
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
#whenever to change of port of eureka server instead of default
# port to need write of below of this line in every service 
eureka.client.service-url.defaultZone=http://localhost:5000/eureka
